### ISSUE TITLE
Thắc mắc về các đặc trưng chứa chữ

### ISSUE THREAD

**Issue by tuandoan998** [hmhuan/Data-science-project#1]
Chào hai bạn,
Mình có thắc mắc về những đặc trưng có dạng chữ như brand, bodyType,... thì các bạn định xử lý như thế nào?

**Comment by hmhuan** [comment]
> Chào hai bạn,
> Mình có thắc mắc về những đặc trưng có dạng chữ như brand, bodyType,... thì các bạn định xử lý như thế nào?

**Comment by hmhuan** [comment]
> Chào hai bạn,
> Mình có thắc mắc về những đặc trưng có dạng chữ như brand, bodyType,... thì các bạn định xử lý như thế nào?

Về các bodyType, brand, .. dạng string hiện tại, thì nhóm mình sẽ xem xét những thuộc tính nào quan trọng sau đó encoding nó sang dạng số để có thể dễ dàng thực hiện các bài toàn máy học. Hiện nhóm vẫn còn vấn đề như thế. Mong thầy và các bạn có góp ý cũng như đánh giá. 
Cảm ơn bạn đã góp ý :)))
