### ISSUE TITLE
Phân chia tập train/validation/test

### ISSUE THREAD

**Issue by tuandoan998** [hmhuan/Data-science-project#3]
Chào nhóm bạn,
Hiện tại mình thấy nhóm bạn có chia tập dữ liệu thành 2 tập train và test, nhưng lại dùng tập test như là một tập validation.
Regards.

**Comment by hmhuan** [comment]
chào bạn,
bên file preprocessing, có tập train mình khi chọn model và siêu tham số, mình tách tập train ra train/val
![image](https://user-images.githubusercontent.com/10975154/71905004-d6b27b80-3199-11ea-8ce7-3341f57479f4.png).
Còn bên file final, là sau khi đã chọn được mô hình và siêu tham số tốt, thì mình mới dùng nguyên tập train để train lại -> sau đó sẽ đo trên tập test
![image](https://user-images.githubusercontent.com/10975154/71905095-06618380-319a-11ea-97fb-2d02c1d9d05f.png)

Cảm ơn bạn đã góp ý và thắc mắc. :v

**Comment by tuandoan998** [comment]
Yay, mình chỉ xem file final.
