### ISSUE TITLE
Quá trình Test 

### ISSUE THREAD

**Issue by trqminh** [hmhuan/Data-science-project#4]
Nhóm bạn cũng nên bổ sung phần đánh giá cho tập dữ liệu test, nếu có thể thì nên có một hàm inference để thử nghiệm trên một ví dụ cụ thể ().

**Comment by hthoai** [comment]
Chào bạn, ở phần cuối của notebook final tụi mình có kiểm tra trên tập test ấy, cụ thể:
- MSE: 22.37 (nghìn USD)
- MAE: 2.472 (nghìn USD)
- R2 score: 0.975
